### ISSUE TITLE
issues with preset?

### ISSUE THREAD

**Issue by eduardoinnorway** [roylee0704/react-flexbox-grid#103] opened 2017-03-24 18:44 UTC
I get,

resolve failed for "eslint-module-utils": Error: Cannot find module 'eslint-module-utils'
resolve failed for "caniuse-db": Error: Cannot find module 'caniuse-db'
resolve failed for "babel-runtime": Error: Cannot find module 'babel-runtime'

**Comment by deltaidea** [comment] 2017-03-24 20:07
How do you reproduce this? Are you sure `react-flexbox-grid` is the reason?

**Comment by eduardoinnorway** [comment] 2017-03-25 01:12
Well this issue came only after installing react-flexbox-grid. I will try again my luck on tomorrow. Coding very late, leads to unexpected misstakes some times :)

**Comment by silvenon** [comment] 2017-03-31 11:11
This errors don't look like they' re related to react-flexbox-grid at all, so I'm closing this until we get more info and confirm that it is indeed related.

**Closed by silvenon** 2017-03-31 11:11 UTC
