### ISSUE TITLE
Feature Request: Hide/Show breakpoints

### ISSUE THREAD

**Issue by boustanihani** [roylee0704/react-flexbox-grid#13] opened 2016-01-27 10:18 UTC
Could you please add a way to show or hide content depending on the screen size (breakpoints)?

Something similar to: http://getbootstrap.com/css/#responsive-utilities-classes
- visible-xs
- visible-sm
- visible-md
- visible-lg
- hidden-xs
- hidden-sm
- hidden-md
- hidden-lg

**Comment by mzgnr** [comment] 2016-01-27 17:29
I can work on this :smiley:

**Comment by mzgnr** [comment] 2016-01-27 17:41
I've looked at the docs of flexboxgrid ; It does not include this feature, am I wrong ? I think we should first contribute to flexboxgrid package for this feature. Any ideas ?

**Comment by roylee0704** [comment] 2016-01-27 18:42
@mzgnr , yes you are right, indeed flexboxgrid.css doesn't support these features. I'm not sure if the author of flexboxgrid would want to have these features, but worth trying. :)

**Comment by boustanihani** [comment] 2016-01-27 19:25
I forgot that I already did a feature request, and there is also a pull request for this, but the author seems not willing to add this feature, check:
- https://github.com/kristoferjoseph/flexboxgrid/issues/138
- https://github.com/kristoferjoseph/flexboxgrid/pull/140

**Comment by mzgnr** [comment] 2016-01-27 20:06
I'm on this feature guys. I'll be back with this feature :)

**Comment by gingur** [comment] 2016-01-29 14:35
I'm in the same boat, I'll be needing to use the bootstrap-ish responsive utils, but I feel that falls outside the scope of what this project was intended for.  If the author of `flexboxgrid` refuses to add it, maybe an extension/utility lib could be implemented to expose that functionality and then wrapped similarly with React components as you guys have done in a separate optional repository.

**Comment by veeracs** [comment] 2016-03-07 04:11
It's a feature that'll make more sense if it's added to a React component as opposed to flexboxgrid because we don't want to render the DOM in the first place based on a media query match and not because of a CSS media query.

**Comment by shilpan** [comment] 2016-03-28 16:29
Any updates on this?

**Comment by silvenon** [comment] 2016-03-28 21:09
@shilpan I don't see how it's accurate to add visibility classes, since flexboxgrid doesn't have this feature, and react-flexbox-grid should just be a React wrapper around flexboxgrid. But I guess it wouldn't hurt :grin:

**Comment by rcherem** [comment] 2016-04-20 18:10
.visible-xs,
.visible-sm,
.visible-md,
.visible-lg {
  display: none !important;
}
@media (max-width: 48em) {
	.visible-xs      { display: block !important; }
	.row.visible-xs  { display: flex !important;
					   display: -webkit-flex !important;
					   display: -ms-flexbox !important;
					   display: -webkit-box !important;
					   display: flex!important; }
	table.visible-xs { display: table !important; }
	tr.visible-xs    { display: table-row !important; }
	th.visible-xs,
	td.visible-xs    { display: table-cell !important; }
}
@media (min-width: 48em) and (max-width: 62em) {
	.visible-sm      { display: block !important; }
	.row.visible-sm  { display: flex !important;
					   display: -webkit-flex !important;
					   display: -ms-flexbox !important;
					   display: -webkit-box !important;
					   display: flex!important; }
	table.visible-sm { display: table !important; }
	tr.visible-sm    { display: table-row !important; }
	th.visible-sm,
	td.visible-sm    { display: table-cell !important; }
}
@media (min-width: 62em) and (max-width: 75em) {
	.visible-md      { display: block !important; }
	.row.visible-md  { display: flex !important;
					   display: -webkit-flex !important;
					   display: -ms-flexbox !important;
					   display: -webkit-box !important;
					   display: flex!important; }
	table.visible-md { display: table !important; }
	tr.visible-md    { display: table-row !important; }
	th.visible-md,
	td.visible-md    { display: table-cell !important; }
}
@media (min-width: 75em) {
	.visible-lg      { display: block !important; }
	.row.visible-lg  { display: flex !important;
					   display: -webkit-flex !important;
					   display: -ms-flexbox !important;
					   display: -webkit-box !important;
					   display: flex!important; }
	table.visible-lg { display: table !important; }
	tr.visible-lg    { display: table-row !important; }
	th.visible-lg,
	td.visible-lg    { display: table-cell !important; }
}
@media (max-width: 48em)                       { .hidden-xs { display: none !important; } }
@media (min-width: 48em) and (max-width: 62em) { .hidden-sm { display: none !important; } }
@media (min-width: 62em) and (max-width: 75em) { .hidden-md { display: none !important; } }
@media (min-width: 75em)                       { .hidden-lg { display: none !important; } }

**Comment by carloscuatin** [comment] 2016-08-16 15:44
You could use a high-level component to do this they think ?

**Comment by silvenon** [comment] 2017-03-23 12:14
Closing this in favor of #57.

**Closed by silvenon** 2017-03-23 12:14 UTC
Labels: enhancement, help wanted
